### ISSUE TITLE
Request support for Intellij IDEA 2022.3

### ISSUE THREAD

**Issue by mrmyn** [rookie-ricardo/BeanMappingKey#4]
**IntelliJ desc**
* IntelliJ platform : 
* Version : 2022.3

**Describe the bug**
Plugin 'BeanMappingKey' (version '2.2') is not compatible with the current version of the IDE, because it requires build 223 or older but the current build is IU-223.7571.182

**Comment by rookie-ricardo** [comment]
好的&nbsp; 尽快解决
&nbsp;


张彦奇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月1日(星期四) 上午9:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: [rookie-ricardo/BeanMappingKey] Request support for Intellij IDEA 2022.3 (Issue #4)





 
IntelliJ desc
  
IntelliJ platform :
 
Version : 2022.3
  
Describe the bug
 Plugin 'BeanMappingKey' (version '2.2') is not compatible with the current version of the IDE, because it requires build 223 or older but the current build is IU-223.7571.182

**Comment by rookie-ricardo** [comment]
> **IntelliJ desc**
> 
> * IntelliJ platform :
> * Version : 2022.3
> 
> **Describe the bug** Plugin 'BeanMappingKey' (version '2.2') is not compatible with the current version of the IDE, because it requires build 223 or older but the current build is IU-223.7571.182

Hi ，The plug-in has been submitted for approval，Support the latest version of ideaSupport the latest version of idea.

**Comment by rookie-ricardo** [comment]
Download in plugin market.
